services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniselec-api
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=uniselec
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www/html
    ports:
      - "8083:80"
    networks:
      - shared-network-uniselec

  db:
    image: mysql:8.0
    container_name: uniselec-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uniselec
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - shared-network-uniselec

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: uniselec-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - shared-network-uniselec

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    container_name: uniselec-redis
    volumes:
      - ./docker/redis:/bitnami/redis/data
    networks:
      - shared-network-uniselec
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=root

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniselec-api.worker
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
      - db
    networks:
      - shared-network-uniselec
    command: "php artisan queue:work redis --tries=3 --verbose"

  # For development and testing
  mailpit: 
    image: axllent/mailpit:latest
    container_name: uniselec-mailpit
    restart: unless-stopped
    volumes:
      - ./docker/mailplit:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - shared-network-uniselec

networks:
  shared-network-uniselec:
    external: true

volumes:
  dbdata:
