# overlays/development/mariadb/backup-restore/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../base/mariadb/backup-restore

patches:
- target:
    kind: CronJob
    name: mariadb-backup-daily
  patch: |-
    - op: replace
      path: /spec/schedule
      value: "0 4 * * *"  # 4 AM em development

    - op: replace
      path: /spec/jobTemplate/spec/template/spec/nodeSelector
      value:
        kubernetes.io/hostname: worker07-ct  # Worker espec√≠fico para dev