apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uniselec-api-dev

resources:
- ../../../../base/mariadb/backup-restore

patches:
- target:
    kind: CronJob
    name: mariadb-backup-daily
  patch: |-
    - op: replace
      path: /spec/schedule
      value: "0 4 * * *"

    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"