apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../base/mariadb/backup-restore

patches:
- target:
    kind: CronJob
    name: mariadb-backup-daily
  patch: |-
    - op: replace
      path: /spec/schedule
      value: "0 4 * * *"