apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount-backup.yaml
  - configmap-backup-scripts.yaml
  - cronjob-backup-daily.yaml
  - job-restore-admin.yaml

# Configurações comuns
labels:
- pairs:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: backup-restore