apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniselec-api
  labels:
    app: uniselec-api
spec:
  selector:
    matchLabels:
      app: uniselec-api
  template:
    metadata:
      labels:
        app: uniselec-api
    spec:
      containers:
      - name: uniselec-api
        image: dti-registro.unilab.edu.br/unilab/uniselec-api:latest
        imagePullPolicy: Always
        # inicialização para garantir permissões
        command: ["/bin/sh"]
        args:
        - -c
        - |
          # permissões  no storage
          chown -R www-data:www-data /var/www/html/storage
          chown -R www-data:www-data /var/www/html/bootstrap/cache
          chmod -R 775 /var/www/html/storage
          chmod -R 775 /var/www/html/bootstrap/cache
          # Iniciar o servidor web
          exec apache2-foreground
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        envFrom:
        - configMapRef:
            name: uniselec-api-config
        # inicio - variáveis do MariaDB
        - configMapRef:
            name: mariadb-env
        - secretRef:
            name: mariadb-secret-env
        # fim - Variáveis do MariaDB
        env:
        - name: TZ
          value: "America/Fortaleza"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_CONTAINER_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: uniselec-api
              resource: limits.cpu
              divisor: 1m
        - name: KUBERNETES_CONTAINER_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: uniselec-api
              resource: limits.memory
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: timezone
          mountPath: /etc/timezone
          readOnly: true
        - name: env-volume
          mountPath: /app/.env
          subPath: .env
        - name: storage-volume
          mountPath: /var/www/html/storage
          subPath: storage
          readOnly: false
        - name: logs-volume
          mountPath: /var/www/html/storage/logs
          subPath: logs
          readOnly: false
        - name: bootstrap-cache-volume
          mountPath: /var/www/html/bootstrap/cache
          subPath: bootstrap-cache
        # garantir permissões para arquivos públicos (se necessário)
        - name: public-volume
          mountPath: /var/www/html/storage/app/public
          subPath: public
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/America/Fortaleza
          type: File
      - name: timezone
        hostPath:
          path: /etc/timezone
          type: File
      - name: env-volume
        configMap:
          name: uniselec-api-config
          items:
            - key: .env
              path: .env
      - name: storage-volume
        persistentVolumeClaim:
          claimName: pvc-uniselec-storage
      - name: logs-volume
        persistentVolumeClaim:
          claimName: pvc-uniselec-logs
      - name: bootstrap-cache-volume
        persistentVolumeClaim:
          claimName: pvc-uniselec-storage
      - name: public-volume
        persistentVolumeClaim:
          claimName: pvc-uniselec-storage
      imagePullSecrets:
      - name: regcred