apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uniselec-api
  annotations:
    haproxy.org/check: "false"
    haproxy.org/forwarded-for: "true"
    haproxy.org/load-balance: "roundrobin"
    haproxy.org/ssl-redirect: "true"
    haproxy.org/ssl-redirect-code: "301"
    haproxy.org/websocket: "true"
spec:
  rules:
  - host: dti-app-test-c1.unilab.edu.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uniselec-api
            port:
              number: 80