apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace padrão (será sobrescrito pelos overlays)
namespace: uniselec-api

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-secret-regcred.yaml
  - hpa.yaml
  - mariadb/
