apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace padrão (será sobrescrito pelos overlays)
namespace: uniselec-api

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc-storage.yaml
  - hpa.yaml
  - sealed-secret-regcred.yaml
  - mariadb/

# Variáveis COMUNS do Laravel (não mudam por ambiente)
configMapGenerator:
  - name: uniselec-api-config
    options:
      disableNameSuffixHash: true
    literals:
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null

      - BROADCAST_DRIVER=log

      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120

      - DB_CONNECTION=mysql
      - DB_PORT=3306

      - MEMCACHED_HOST=127.0.0.1
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.noreply.unilab.edu.br
      - MAIL_PORT=25
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_ENCRYPTION=

      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false

      - PUSHER_APP_ID=
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - PUSHER_HOST=
      - PUSHER_PORT=443
      - PUSHER_SCHEME=https
      - PUSHER_APP_CLUSTER=mt1

      - VITE_APP_NAME=${APP_NAME}
      - VITE_PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - VITE_PUSHER_HOST=${PUSHER_HOST}
      - VITE_PUSHER_PORT=${PUSHER_PORT}
      - VITE_PUSHER_SCHEME=${PUSHER_SCHEME}
      - VITE_PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
